# This isn't all the SciPy modules...
modules = ['cluster', 'differentiate', 'fft',
           'integrate', 'interpolate', 'linalg', 'optimize',
           'signal', 'sparse', 'spatial', 'special', 'stats']

for src in ['nightly']:
    tmpl = open(f"xslow-{src}.template").read()

    for module in modules:
        filename = f"xslow-{src}-{module}.yml"
        with open(filename, 'w') as f:
            f.write("# Do not edit this file.  To update the yml files, update the\n")
            f.write("# template file and run generate.py.\n\n")
            f.write(tmpl.replace("{MODULE}", module))
