
# This isn't necessarily all the SciPy modules...
modules = ['cluster', 'differentiate', 'fft',
           'integrate', 'interpolate', 'linalg', 'optimize',
           'signal', 'sparse', 'spatial', 'special', 'stats']

tmpl = open('xslow-nightly.template').read()

for module in modules:
    filename = f"xslow-nightly-{module}.yml"
    with open(filename, 'w') as f:
        f.write("# Do not edit this file.  To update the files named "
                "xslow-nightly-MODULE.yml,\n")
        f.write("# update xslow-nightly.template and run generate.py.\n\n")
        f.write(tmpl.replace("{MODULE}", module))
