name: scipy build, xslow tests

on:
  workflow_dispatch:
    inputs:
      module1:
        description: 'SciPy module to test'
        required: true
        type: choice
        options:
          - none
          - cluster
          - differentiate
          - fft
          - integrate
          - interpolate
          - linalg
          - optimize
          - signal
          - sparse
          - spatial
          - special
          - stats
      module2:
        description: 'SciPy module to test'
        required: true
        type: choice
        options:
          - none
          - cluster
          - differentiate
          - fft
          - integrate
          - interpolate
          - linalg
          - optimize
          - signal
          - sparse
          - spatial
          - special
          - stats
      module3:
        description: 'SciPy module to test'
        required: true
        type: choice
        options:
          - none
          - cluster
          - differentiate
          - fft
          - integrate
          - interpolate
          - linalg
          - optimize
          - signal
          - sparse
          - spatial
          - special
          - stats

jobs:

  xslow-test:
    name: xslow-test ${{ inputs.module1 }} ${{ inputs.module2 }} ${{ inputs.module3 }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.14']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      SCIPY_XSLOW: 1

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update python pip, wheel, setuptools
        run: |
          python -m pip install --upgrade pip wheel setuptools
      - name: Install libopenblas-dev
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libopenblas-dev
      - name: Clone the scipy repo
        run: |
          git clone --shallow-submodules --recurse-submodules https://github.com/scipy/scipy.git
      - name: Install build, dev and test requirements
        run: |
          cd scipy
          pwd
          python -m pip install --group build --group test --group dev-cli
      - name: Test ${{ inputs.module1 }}
        if: ${{ inputs.module1 != 'none' }}
        run: |
          cd scipy
          pwd
          spin test -m full -j 2 -s ${{ inputs.module1 }} --durations 10
      - name: Test ${{ inputs.module2 }}
        if: ${{ inputs.module2 != 'none' }}
        run: |
          cd scipy
          pwd
          spin test -m full -j 2 -s ${{ inputs.module2 }} --durations 10
      - name: Test ${{ inputs.module3 }}
        if: ${{ inputs.module3 != 'none' }}
        run: |
          cd scipy
          pwd
          spin test -m full -j 2 -s ${{ inputs.module3 }} --durations 10
